### ISSUE TITLE
Add Dynamic PR Comments with Build Status

### ISSUE THREAD

**Issue by callogan** [canonical/github-runner-operator#465]
### Enhancement Proposal

Summary:
Improve the existing pull request comment workflow by adding dynamic comments that include the PR author and the current build status. This will enhance communication and provide real-time updates directly in the pull request.

Proposed Changes:

Modify the comment_contributing.yml workflow to post dynamic comments on PRs.
Comments will include:
The PR author (@username).
The current PR state (opened, closed, etc.).
A success/failure message based on the build result (if applicable).
Use GitHub API to post comments directly to the PR.
Benefits:

Clear and immediate feedback on the status of the pull request.
Improved team collaboration with automated status updates.
Reduces manual efforts to check build results and PR metadata.

Example Implementation:
```yaml
jobs:
  comment-on-pr:
    uses: canonical/operator-workflows/.github/workflows/comment_contributing.yaml@main
    secrets: inherit
    steps:
      - name: Add dynamic PR comment with status
        run: |
          pr_url="https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }}/comments"
          message="🚀 PR opened by @${{ github.actor }}. Current PR status: *${{ github.event.pull_request.state }}*."
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -d "{\"body\":\"$message\"}" $pr_url
```
This improvement will make the workflow more interactive and valuable to contributors and reviewers.
